### ISSUE TITLE
Feature Request: T-Beam SUPREME Support

### ISSUE THREAD

**Issue by cacula** [gereic/GXAirCom#124]
Hi,
just saw that there will be a new T-Beam Version: https://s.click.aliexpress.com/e/_DExCX4d
Looks like they did a coop with softrf: https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkIII
Any Plans on supporting it?
Cheers

**Comment by jtoloe** [comment]
Support for this board would be great. Looks like it would be perfect for a gxaircom variometer. Comes with BME280, 6 axis IMU and SD card writer already on the board.

**Comment by gereic** [comment]
I anybody sends me a Board, I can try to support it.

**Comment by gereic** [comment]
I live in Austria, so 868Mhz is perfect.

**Comment by gereic** [comment]
sorry, can't find your e-mail.
please send a e-mail to gerald.eichler(a)mgenet.at

**Comment by VirusPilot** [comment]
I would also welcome support for the T-Beam S3 Supreme and particularly the S3Core board which nicely fits into a Stratux to add transmission functionality, see here:

![IMG_1531](https://github.com/gereic/GXAirCom/assets/43483458/aef997f1-41f5-4a95-b289-5f23b2804296)

**Comment by gereic** [comment]
S3Core is supported since v5.3.5

**Comment by YetAnotherModelShip** [comment]
> I live in Austria, so 868Mhz is perfect.

Hallo gereic. Ich habe ein T-beam supreme board und es hat ein Programm drauf, das die Sensoren etc. anzeigt. Was muss ich tun, um meine eigenen Sketches, die ich in Arduino 2 schreibe, darauf laufen zu lassen? Die Arduino IDE bricht mit Fehlermeldung dass sie nicht uploaden kann ab. Board Verbindung klappt grundsätzlich ... Ich bin ratlos, vielleicht fällt dir was ein. Muss ich etwas Flashen? Tasten betätigen? Danke für deine Antwort.

**Comment by Oli-70** [comment]
Did anyone test this board with the built-in display? It doesn't work for me. (#221)

**Comment by Oli-70** [comment]
> Did anyone test this board with the built-in display? It doesn't work for me. ([#221](https://github.com/gereic/GXAirCom/issues/221))

Fixed! The issue is that some T-Beam S3 Supreme revisions use the 0x3C address for the built-in magnetometer (QMC6310N), which conflicts with the default OLED address. Because of this, the display needs to be addressed via 0x3D.

I'm not able to implement the full dynamic auto-detection logic, so I just hardcoded it to 0x3D. Maybe someone with more development experience can use this as a base and implement the proper auto-detection – which was already developed by the Meshtastic community and which I explained in more detail in issue #221 – so it works out-of-the-box for everyone.

More details here: https://github.com/gereic/GXAirCom/issues/221#issuecomment-4720580289
